### ISSUE TITLE
Mobile theme menu bug

### ISSUE THREAD

**Issue by Mukhammadali** [siteorigin/siteorigin-unwind#105]
Hi guys, i installed your unwind theme. Firstly thank you very much for this kind of free source. But I should inform you about the bug when i  accessed my wbesite on mobile devices, Mobile device original browsers and other browsers such as Chrome, Firefox are also showing some bugs in the theme when i clicked on the menu button , after opening menu there are my pages and menu sections, there the number of cart menus are increasing and decreasing and when i clicked on the electronics menu arrow to open sub menu under it sub menu is automatically opening and closing in seconds after trying 3 4 times it is working. and this bug is always happening. I thought problem maybe with my confguration on my wordpress. but i tested this on the demo on your siteorigin website and the same bug also exists there. I checked in seveeral mobile devices by different manufacturers and it happens with all of them. So can you check it out and fix that or make some instructions to fix . I uploaded some screenshots below. Thanks in advance

![screenshot_2017-02-04-05-53-16](https://cloud.githubusercontent.com/assets/22298895/22608213/f860360e-ea9e-11e6-945b-4bbe6a3eeaec.png)
![screenshot_2017-02-04-05-53-20](https://cloud.githubusercontent.com/assets/22298895/22608215/fc1b96a8-ea9e-11e6-90b4-5dbc5a40b10e.png)

**Comment by adiraomj** [comment]
@Mukhammadali can you provide me with a link to your site where this problem exists. Thanks.

**Comment by Mukhammadali** [comment]
@adiraomj  https://aliexhelp.com here you can check it. Just click on the menu button multiple times then cart multiplies then at that time try to open sub menu.
