### ISSUE TITLE
Mini Cart - View Cart button not affected by styling

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#107]
The View Cart button isn't affected by the accent styling setting [due to this CSS](https://github.com/siteorigin/siteorigin-unwind/blob/develop/sass/woocommerce/_cart.scss#L536). 

Is this intended? I ask as it's _very_ odd that this is the only button not affected by accent coloring.

![](https://i.imgur.com/8rfy2eC.png)

**Comment by adiraomj** [comment]
It was not intended. There was a problem with the generated settings custom CSS. Sending PR now. ;)
