### ISSUE TITLE
Product Gallery compatibility with WooCommerce hooks

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#109]
A few users have reported that the Unwind Product Gallery isn't compatible with the default WooCommerce product gallery. This normally isn't a huge problem but when users use plugins that extend the base WooCommerce gallery, it won't work. I can see two possible solutions, a setting that defaults to the default WooCommerce gallery or compatibility with the product gallery. The latter being the ideal solution.

An example plugin is [WooCommerce Additional Variation Images
](https://woocommerce.com/products/woocommerce-additional-variation-images/)

**Comment by IbrahimRumani** [comment]
Approximately by when will this bug be fixed ?

**Comment by Misplon** [comment]
Hopefully, next week, sorry for the delay.

**Comment by IbrahimRumani** [comment]
That's great!
