### ISSUE TITLE
Theme logo

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#11]
I was thinking of using WP's new responsive images for the logo, instead of how we did it with SO north. What do you think?

https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

**Comment by gregpriday** [comment]
I'm definitely keen on using core WordPress functionality for this. How would this work though? So when a user uploads a logo, they'd usually expect that logo to be displayed with the exact dimensions that they upload it.

From what I understand about responsive images in WP 4.4 is that each image just includes all the extra image sizes that are available. But how would we go about making sure the exact sizes we need are available.

**Comment by adiraomj** [comment]
Sorry. This is my mistake. Read up  a little bit more on the new responsive images feature. 

Correct me if I am wrong, but the responsive images feature is only used to load different image sizes based on viewport size. What we need is to load images based on image density (eg: 1x, 2x, 3x, etc..). 

So I guess we cannot use it in this scenario..

**Comment by gregpriday** [comment]
Yeah, I think it would be a little complicated using this core functionality. Would have been nice, but the way we're using `srcset` is quite specific.
