### ISSUE TITLE
Two column & three column layout for the blog + WooCommerce

### ISSUE THREAD

**Issue by IbrahimRumani** [siteorigin/siteorigin-unwind#111]
Enhancements:

WooCommerce Integration: An option to display the thumbnails on the left instead of bottom would be good.

Blog view: Two column and Three column layout.

**Comment by Misplon** [comment]
Hi, thanks for posting. New blog layouts on the way soon but we didn't have anything lined up for the WooCommerce gallery setting. That's a good idea, I'll chat to the team about it.

**Comment by IbrahimRumani** [comment]
Approximately by when would the new blog layouts be available ?

**Comment by Misplon** [comment]
Sorry for the delay, I'm not sure yet, this addition will most likely be pushed in the first half of March.

**Comment by IbrahimRumani** [comment]
When are you planning to add two column layouts ?

**Comment by adiraomj** [comment]
Implemented with #121.
Added option to have between 2 to 5 columns.

**Comment by Misplon** [comment]
WooCommerce option has been added, additional blog options still to be added. Working on getting the update out with the new header layouts.
