### ISSUE TITLE
SiteOrigin Social Media button theme margin/padding is more specific than padding generated by widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#114]
[The margin and padding](https://github.com/siteorigin/siteorigin-unwind/blob/develop/sass/navigation/_menus.scss#L170) are more specific than the CSS generated by the SiteOrigin Social media buttons widget so it's impossible for the user to adjust it without manually writing CSS.

![](https://i.imgur.com/JqfBAsQ.png)

**Comment by adiraomj** [comment]
@Misplon remember why https://github.com/siteorigin/siteorigin-unwind/commit/859d0700c7d18d11f86bec1d85dfb4b5d704511c was done? ;)

**Comment by Misplon** [comment]
Phew, not sure. Let's fix this issue, I'll check for knock on issues in the demo once it's done.
