### ISSUE TITLE
Mini Cart - Improve Variation styling

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#115]
The product variations in the mini cart really don't like good. We should line the variations with the title, as in, to the right of the image.

How it currently looks:
![](https://i.imgur.com/ifLpBsl.png)
![](https://i.imgur.com/G3vOQvu.png)

Here's an example of what would look better:
![](https://i.imgur.com/8dhOoSm.png)

Thoughts?

**Comment by adiraomj** [comment]
@AlexGStapleton I have included this in #110.

Please test and let me know what you think. :)

**Comment by AlexGStapleton** [comment]
Oh. Somehow missed that! :(

Yeah, that looks _much_ better. 👍
