### ISSUE TITLE
Social Profiles

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#12]
For the social profile icons in the header, I was thinking of adding a new section in the settings dedicated to **Social Profiles**.  And then supporting all profiles that are supported in Jetpack's social media icons widget. What did you have in mind?

https://jetpack.me/support/extra-sidebar-widgets/social-media-icons/

**Comment by gregpriday** [comment]
The way we've done this in Vantage is just to add a header widget area, then let the user add a social profiles widget like the one in the Widgets Bundle or an alternative like Jetpack's widget.

Yet another option we have, and this would take a lot more work, would be to create a widget settings field. Our old settings framework used to have this, before we moved everything over to the customizer.

So in this case, we could have a single setting that lets the user select a widget from a dropdown, then build that widget right there in the settings. This could give a very cool experience and we could encourage users to install the Widgets Bundle and/or Jetpack.

I'll take a look at how difficult this would be to implement in the customizer.

**Comment by adiraomj** [comment]
I will check out vantage and try to implement something similar. 

Adding the option for users to add widgets in the settings is super cool.. Hope its possible. I'm psyched reading about it. Will definitely give users much more control over the theme.

**Comment by gregpriday** [comment]
I'll play around and see if I can get this working.

**Comment by Misplon** [comment]
@gregpriday I think this setting field is ready now, is that correct?

**Comment by gregpriday** [comment]
The widget setting field? Yup! Ready and waiting in the latest settings framework. You can see it in action in Influence.

https://github.com/siteorigin/influence/blob/develop/inc/settings.php#L90-L96
https://github.com/siteorigin/influence/blob/develop/inc/slider.php#L14-L17

**Comment by adiraomj** [comment]
Cool. I will check it out.

**Comment by adiraomj** [comment]
@gregpriday what should the default value of the social widget be?

**Comment by gregpriday** [comment]
I think it'll give a really smooth experience. By default maybe it should link to the big 3 networks. Just make sure that it only links to `#` by default. Or we could just leave it empty by default?

**Comment by adiraomj** [comment]
I feel leaving it empty would be the best.

**Comment by adiraomj** [comment]
Jetpack added [Social Profiles](https://jetpack.com/support/social-menu/) earlier this year. How about using it as a fallback for users who do not have the Widgets Bundle installed or have left the field empty?

**Comment by gregpriday** [comment]
We could definitely do that. Does Jetpack also control the visual style of the profiles?

**Comment by adiraomj** [comment]
@gregpriday I tried out Jetpack's Social Profile feature. It doesn't look like there are any options for styling. Maybe we can add it in future if more options are available. :)

**Comment by Misplon** [comment]
This has been completed.
