### ISSUE TITLE
[FireFox] Coupon Checkout field: Unable to see contents of field

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#130]
The coupon field on the checkout page has the exact same amount of padding as it does height. This, as a result, is causing the contents of the field to not be visible.

[This can be replicated on the demo](https://demo.siteorigin.com/unwind/shop/cart/).
![](https://i.imgur.com/f50Jj22.gif)

**Comment by Misplon** [comment]
https://github.com/siteorigin/siteorigin-unwind/commit/5fb635a8de8173eeefb9013389aba4be88eeb5c3
