### ISSUE TITLE
.Sticky-bar low z-index is causing floating menu to appear under high z-index elements

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#144]
[This z-index](https://github.com/siteorigin/siteorigin-unwind/blame/develop/sass/site/header/_masthead.scss#L14) needs to be increased as currently it's resulting in sliders and anything with a high z-index to appear on top of the menu when its floating.

**Comment by Misplon** [comment]
Meant to log this, thanks. Noticed the Sale sticker on the shop page were on top of the menu too.
