### ISSUE TITLE
Sticky Menu: change transition to sticky menu to be more fluid

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#145]
The current transition from normal to sticky for the menu is quite jarring at the moment. Ideally, as soon as the browser scrolls past the point of where the top of the menu is, the menu should become stuck to the top of the screen to prevent the menu from jumping back to the top of the browser when the user scrolls past bottom of the menu.

Thoughts?

![](https://vgy.me/xvqD4k.gif)

**Comment by Misplon** [comment]
@adiraomj Is the same as North? We chatted about the scroll point on Slack the other day. Any ideas?
