### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by knightknight** [siteorigin/siteorigin-unwind#148]
`Warning: A non-numeric value encountered in /domain.com/wp-content/themes/siteorigin-unwind/inc/settings/settings.php on line 475`

- SiteOrigin UnwindVersion: 1.0.13
- Page Builder Version 2.5.6
- SO Widgets Bundle Version 1.9.2

**Comment by AlexGStapleton** [comment]
This issue has been reported [here](https://github.com/siteorigin/settings/issues/37).

**Comment by Misplon** [comment]
Thanks @knightknight, appreciate the issue report. We'll attend in the settings repo. Once resolved there, settings will get updated in Unwind (it's a sub-module). Cheers :)
