### ISSUE TITLE
Sidebar responsive CSS doesn't work when sidebar position set to left

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#156]
The selector used to allow for the [.content-area](https://github.com/siteorigin/siteorigin-unwind/blob/develop/style.css#L1431) to become full width on mobile devices is not as specific as the selector applied to the sidebar when it's set to display on the left [.main-sidebar-left .content-area](https://github.com/siteorigin/siteorigin-unwind/blob/develop/sass/layout/_layout.scss#L71).

![](https://i.imgur.com/f9L4DAi.png)

There could be other specificity issues related to [.main-sidebar-left](https://github.com/siteorigin/siteorigin-unwind/blob/develop/sass/layout/_layout.scss#L70) so it would be a good idea to take a look over all of them just to be sure.

This is similar to siteorigin/siteorigin-north#297

**Comment by Misplon** [comment]
We'll resolve and include the fix in Monday's update.
