### ISSUE TITLE
Homepage slider

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#16]
1. For the query, we can use [Jetpack's Featured Content](https://jetpack.me/support/featured-content/). This is what has been done in the components magazine starter theme. 

2. We can add an option to exclude the posts in the slider from the posts query.

3. Is there a script you have in mind to use for the slider?

4. We can add a `Front Page` template which has the slider on top by default.

**Comment by Misplon** [comment]
@gregpriday I like @adiraomj's plan here. Which slider script do you want to use? Flexslider?

**Comment by Misplon** [comment]
@adiraomj 

1. I'm cool with that. @gregpriday, you down?

2. Sounds good.

3. Flexslider? @gregpriday 

4. Sounds good. @gregpriday

**Comment by Misplon** [comment]
@adiraomj Spoke to @gregpriday. All sounds good. Do you want to use Flexslider? Let's get this done.
