### ISSUE TITLE
Menu in line Logo: masthead_padding sizing isn't calculating correctly

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#161]
[This line](https://github.com/siteorigin/siteorigin-unwind/blob/1.1.0/inc/settings.php#L487) and [this line](https://github.com/siteorigin/siteorigin-unwind/blob/1.1.0/inc/settings.php#L621) aren't calculating.

![](https://i.imgur.com/FQRMgtI.png)
![](https://i.imgur.com/HbqRAJL.png)

**Comment by Misplon** [comment]
![cpqusw1](https://user-images.githubusercontent.com/789159/28186658-50df0260-681c-11e7-86af-8f534cc8d83d.png)

No joy

**Comment by Misplon** [comment]
@AlexGStapleton, @gregpriday going to make a change to the settings framework to handle some basic maths.

**Comment by AlexGStapleton** [comment]
Awesome! 😃
