### ISSUE TITLE
Video Post Type: Second video is removed

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#163]
If two videos are added to a video post, the second video is removed.

**Comment by VadymVolos** [comment]
Hi!

It is also necessary to add:  `?rel=0&amp;`
in video and playlist.
https://developers.google.com/youtube/player_parameters

Example:
```
https://youtu.be/BmBh0NNEm00
https://youtu.be/BmBh0NNEm00?rel=0

https://www.youtube.com/watch?v=BmBh0NNEm00
https://www.youtube.com/watch?v=BmBh0NNEm00?rel=0

<iframe width="853" height="480" src="https://www.youtube.com/embed/BmBh0NNEm00?rel=0" frameborder="0" allowfullscreen></iframe>

```

Example playlist:
```
https://youtu.be/k_okcNVZqqI?list=PLD33E5618740295DF
https://youtu.be/k_okcNVZqqI?rel=0&amp;list=PLD33E5618740295DF

https://www.youtube.com/embed/k_okcNVZqqI?list=PLD33E5618740295DF
https://www.youtube.com/embed/k_okcNVZqqI?rel=0&amp;list=PLD33E5618740295DF

<iframe width="853" height="480" src="https://www.youtube.com/embed/k_okcNVZqqI?rel=0&amp;list=PLD33E5618740295DF" frameborder="0" allowfullscreen></iframe>

```

**Comment by VadymVolos** [comment]
And, when added playlist - not work playlist:

`https://youtu.be/k_okcNVZqqI?list=PLD33E5618740295DF`

**Comment by Misplon** [comment]
Hi @VadymVolos. The playlist link provided renders the same whether I use Unwind or Twenty Sixteen. Please, try switching themes and check the issue, I don't think it's related to Unwind. The main issue (second video removed) has been resolved, we'll update soon.
