### ISSUE TITLE
Gallery Post Type: img background-size cover not work

### ISSUE THREAD

**Issue by VadymVolos** [siteorigin/siteorigin-unwind#164]
Gallery Post Type (img size cover)
background-size: cover;
not work

When different sizes of images, on some slides there's an emptiness at the bottom.

**Comment by Misplon** [comment]
Hi :) Thanks for posting. The images are inserted using an `HTML` `img` tag so it won't be possible to use the `background-size` property. Images would need to be background images inserted with CSS for this to work, that isn't the case.

You can see the gallery creation here: https://github.com/siteorigin/siteorigin-unwind/issues/153.

Unfortunately, at this stage, I can't think of a solution for your problem. One idea I had was to somehow use an image size defined by the theme but it doesn't appear that's possible: https://wordpress.stackexchange.com/questions/4563/add-image-size-for-specific-post-types.

**Comment by VadymVolos** [comment]
Thanks for answer.
#153

**Comment by VadymVolos** [comment]
The solution to the problem: in the header slider there is no problem.

**Comment by Misplon** [comment]
Cool, let me chat to the team about this as a possible change.

**Comment by Misplon** [comment]
Hi @VadymVolos We're going to leave the gallery as is for the moment. One idea might be to create a custom thumbnail size using Simple Image Sizes, regen. your thumbnails and then add your gallery using that image size or use one of the existing image sizes in your WordPress installation. The image size setting is available in Gallery Settings in the right column when editing the gallery.
