### ISSUE TITLE
Page Settings

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#17]
Which page settings do you think we should add to the theme?

1. Layout : default, full-with, no-sidebar and full-width no-sidebar.

2. Page title : display or not?

What do you think? Any others to add?

**Comment by gregpriday** [comment]
I think going for something similar to what we have with [North](https://github.com/siteorigin/siteorigin-north/) is ideal. Assuming the header and footer margin settings work with the Unwind design.

I can't think of any other good settings at the moment. The settings we have in North cover the vast majority of use cases, but I'm sure there are some more we might think of.

**Comment by adiraomj** [comment]
I have used margins for the `#masthead` and `#colophon`. We should easily be able to accommodate the header and footer margin settings. : )

**Comment by gregpriday** [comment]
I think we can leave out the _menu overlaps content_ setting for this theme. That setting seems to suit more generic/multipurpose themes like North, whereas Unwind is more of a pure blogging theme to me. Also, as you mentioned, it'll be hard to make this design work with the masthead overlapping the content.
