### ISSUE TITLE
WooCommerce: Sold Individually setting doesn't currently work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#195]
Due to how we implement the quantity buttons ([reference](https://github.com/siteorigin/siteorigin-unwind/blob/release/1.1.2/js/woocommerce.js#L5)), the Sold Individually WooCommerce settings don't currently work. 

[Slack Reference](https://siteorigin.slack.com/archives/C02SXRL8N/p1509439381000273)
[Reported in this thread](https://siteorigin.com/thread/removing-quantity-and-from-product-page/)

**Comment by Misplon** [comment]
@adiraomj Think you could take a look for us?
