### ISSUE TITLE
Mobile Menu: Non link menu items should open sub menus

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#199]
Mobile Menu should allow for menu items that don’t have a link set (or are set to #) to open the submenu on click rather than doing nothing.

**Comment by Misplon** [comment]
@adiraomj Reckon you can take a look for us? 

Possible solution here: https://siteorigin.com/thread/solution-to-making-the-parent-menu-item-clickable-to-toggle-submenu-items/, not that you need it :) Nice user though.
