### ISSUE TITLE
Customizer: Changes to menu when in mobile view aren't reflected

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#201]
Changes to the menu when in mobile view aren't reflected until changes are published and customizer reloaded. The normal desktop menu is correctly updated.

![](https://i.imgur.com/DRiLmPv.gif)

**Comment by Misplon** [comment]
Mmm not sure how we'd fix this. The mobile menu is cloned from the main menu. Have there been complaints about this?

**Comment by AlexGStapleton** [comment]
No. Only one person has reported this issue so far.

**Comment by Misplon** [comment]
@adiraomj Are there any easy solutions to have changes in the menu reflect in the mobile menu in the Customizer?

**Comment by Misplon** [comment]
Super, thanks.

**Comment by adiraomj** [comment]
I could not figure out the solution. Any ideas @gregpriday ?

**Comment by Misplon** [comment]
I happy to close for the moment guys. If there is more attention on improving this functionality, we can revisit.
