### ISSUE TITLE
Mobile menu scroll issue with sticky menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#209]
When you have a large menu and have it set to sticky, on mobile it becomes problematic to scroll as scrolling will very likely trigger the sticky menu which prevents the mobile menu scroll from working correctly. I think we should disable screen scroll when the mobile menu is open and it's larger than the size of the screen (similar to #43.)

Reference GIF:
![](https://i.imgur.com/mS36Fv4.gif)

(I have no idea why my cursor isn't visible but basically I'm trying to scroll the mobile menu)

**Comment by Misplon** [comment]
@AlexGStapleton Nice catch. Didn't we do that in North? If so, let's roll out the same thing.

**Comment by AlexGStapleton** [comment]
Not exactly, but something very similar. Basically, we added an overflow that allows you to scroll the mobile menu and not the page itself.
