### ISSUE TITLE
Search breaks if Wordpress in sub directory

### ISSUE THREAD

**Issue by m9n** [siteorigin/siteorigin-unwind#220]
My normal structure for WordPress has WP in a subdirectory.  My wp-config looks like this:
```
/**
 * Define Site URL: WordPress in a subdirectory.
 */
define( 'WP_SITEURL', 'http://example.com/wordpress' );
define( 'WP_HOME', 'http://example.com' );

/**
 * Define path and url for wp-content.
 */
define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content' );
define( 'WP_CONTENT_URL', WP_HOME . '/wp-content' );
```

While this isn't everybody's normal, it's not uncommon, and helps keep things tidy if you want to version control all your plugins and themes (core wordpress folder just gets.gitignored).

Problem is, because the search forms in Unwind use `site_url()` as their action, they send people to http://example.com/wordpress?s=searchterm - which results in a 404.

If unwind used `home_url()` instead, there'd be no problem:
https://codex.wordpress.org/Function_Reference/home_url

Hope this can be changed.  For now, you're forcing me to either work in a specific way with WordPress, or directly hack Unwind, or maintain unnecessary templates in a child theme.

**Comment by Misplon** [comment]
Thanks @m9n. Sorry for the hassle! Will resolve shortly and get a release out hopefully later this week, latest early next week.

**Comment by m9n** [comment]
@Misplon you're a star.  Thank you!
