### ISSUE TITLE
Portfolio loop: Enhance to allow Post Loop widget filtering

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#224]
At the moment, it isn't possible to use the Post Loop widget, select the Portfolio template and specify a taxonomy. For example: `jetpack-portfolio-type:europe`, assuming `europe` was the project type we wanted to display on the page. Eg: http://demo.siteorigin.com/unwind/project-type/europe/

**Comment by Misplon** [comment]
Hi @dexgen As of the `1.2.15` release you'll be able to use Taxonomy filtering in the Post Loop widget, for example, if you had a Type called Europe, you could insert: `jetpack-portfolio-type:europe`. 

Access to posts, not just yet. Thanks.

**Comment by dexgen** [comment]
Thanks!

**Comment by Misplon** [comment]
Hi @dexgen 

We'd need to create a new post loop to filter regular posts in the same format/design as the portfolio loop.

Do you perhaps want to try the Livemesh Grid widget, it should let you do the same right now.

https://wordpress.org/plugins/livemesh-siteorigin-widgets/
https://www.livemeshthemes.com/siteorigin-widgets/portfolio-grid/

**Comment by Misplon** [comment]
Widgets for SiteOrigin has a Portfolio widget too that should accept posts: https://wordpress.org/plugins/widgets-for-siteorigin/

However, Adi mentioned to me he's working on this now so we should have a new loop in Unwind this week.

**Comment by Misplon** [comment]
To be included in next release :) Thanks.

**Comment by Misplon** [comment]
Hi @dexgen

We're having reservations about introducing a new post loop for Unwind. Sorry for the back and forth. The Grid widget added by LiveMesh Widgets https://wordpress.org/plugins/livemesh-siteorigin-widgets/ would be the one to use for a portfolio type look but with posts.

Sorry for the hassle. Let me know if you have any follow-up questions.

**Comment by Misplon** [comment]
Hi @dexgen 

Thanks for your feedback (not shown here). 

The Post Loop widget is contained in Page Builder, we can't easily filter its field contents from within Unwind. What I will do is include a note in the Portfolio Loop name to indicate it is only for Jetpack projects.

Have you made progress with the Grid widget from LiveMesh to add a grid for your posts that is filterable?
