### ISSUE TITLE
Build issue with pot file: directory incorrectly named as siteorigin-unwind.pot 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#240]
[The build issue with the pot file](https://github.com/siteorigin/vantage/issues/264) that was affecting Vantage is also affecting Unwind now. 
![](https://i.imgur.com/jZR5uor.png)

**Comment by Misplon** [comment]
Re-built `node_modules`. Issue will be resolved in next release build.
