### ISSUE TITLE
Search button is not visible when fullscreen-search is active

### ISSUE THREAD

**Issue by fcojgodoy** [siteorigin/siteorigin-unwind#242]
Z-index is missing in `#search-button`.

I'd like to help. Do you accept collaborations?

Maybe this:

```
.header-design-3 .social-search .search-toggle,
.header-design-4 .social-search .search-toggle {
    z-index: 15;
}
```

**Comment by AlexGStapleton** [comment]
Nice find. We do accept [pull requests](https://help.github.com/articles/about-pull-requests/)! Please feel free to submit one. 👍
