### ISSUE TITLE
Theme Logo

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#25]
How about implementing the new [**Custom Logo**](https://codex.wordpress.org/Theme_Logo) from Unwind onwards?

**Comment by gregpriday** [comment]
I like the idea of using the custom logo feature as a fallback. So it a user has uploaded one, we'll support it. I've already added this to Origami.

How does the custom logo feature handle retina logos?

**Comment by Misplon** [comment]
@adiraomj Can you implement this for us? Let's implement the same as we have in North. Thanks :)

**Comment by adiraomj** [comment]
@Misplon I don't think we have implemented the custom logo feature in North. We did it in Vantage and Focus.
