### ISSUE TITLE
Menu widget atom theme 404

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#27]
@adiraomj Could you please, take a look at this for us:

<img width="1432" alt="atom-issue" src="https://cloud.githubusercontent.com/assets/789159/19012693/47b56c82-87bd-11e6-9da3-b40ca0bc816f.png">

Thanks bro :)

**Comment by adiraomj** [comment]
@Misplon the idea was to stay as close to Ricardo's design as possible. Which is why, we used a padding of **Low** during initial development. Any padding above that tends to break our design. What padding did you use?

**Comment by adiraomj** [comment]
Issue seems to have sorted itself out. 👍
