### ISSUE TITLE
Cart Widget: Enhance to show the selected variation image

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#273]
The mini-cart and cart widget don't show the selected variation image.

**Comment by AlexGStapleton** [comment]
The variation image isn't appearing due to [this](https://github.com/siteorigin/siteorigin-unwind/blame/develop/woocommerce/functions.php#L124-L129). How do you want to proceed? Do you want to remove that code (and the related Image Size) or account for variation product images?

**Comment by Misplon** [comment]
I suppose from a performance point of view, it isn't ideal to load a big image when we just need the tiny thumbnail. If we can account for the variation, that would be ideal.
