### ISSUE TITLE
WC Quick View: Add image change when variations selected

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#281]
Add image change when variations are selected as you see on the main product page for variable products.

**Comment by AlexGStapleton** [comment]
@Misplon I've looked into and this can be done two ways.

1. We replace the existing flexslider markup with the [standard WooCommerce product gallery template](https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-image.php). This should be faster, but we'll need to fight WooComemrce to get the slides to be the same size as they are now.

2. We extend the current setup to allow for this. This will take longer, but we won't need to fight WooCommerce.

Which route do you want me to take? I'm guessing 2, but want to confirm so we're on the same page.

**Comment by Misplon** [comment]
Option 2, thanks mate.
