### ISSUE TITLE
Sharing in single posts

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#3]
To add sharing buttons for single posts, I can see 2 ways we can go about it.

1. we add our own sharing buttons.

2. we can use Jetpacks Sharing module.

I vote for Jetpack. Gives the users more control over services and the UI. (and less coding for us.. hehehe)

**Comment by gregpriday** [comment]
As far as I remember, themes aren't allowed having sharing buttons (by the
wp.org theme review requirements). So Jetpack support is the solution here.

**Comment by Misplon** [comment]
Sharing is considered plugin functionality so unfortunately, we can't include our own. The Jetpack Sharing module is really nice, let's support that.

**Comment by adiraomj** [comment]
Cool. Will do it.

**Comment by Misplon** [comment]
Done.
