### ISSUE TITLE
Check on review potential errors raised

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#314]
Ref: [118237](https://themes.trac.wordpress.org/ticket/118237#comment:2)

**Comment by AlexGStapleton** [comment]
Reported error points to usage of `play()` without interaction but [we don't use play() anywhere](https://github.com/siteorigin/siteorigin-unwind/search?q=play). I've attempted to replicate this issue but haven't been able to. I've tested using both the [test theme data](https://github.com/WPTT/theme-test-data/blob/master/themeunittestdata.wordpress.xml) and the [theme review action](https://github.com/WordPress/theme-review-action/blob/trunk/config/a11y-theme-unit-test-data.xml). I'm suspect this report is a false positive so I'm going to close this for now and we'll pick this back up if it gets reported again.
