### ISSUE TITLE
WooCommerce: Check out of stock button positioning and styling

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#319]
@AlexGStapleton I think let's style the Read More button the same as Add to Cart on hover.

![read-more](https://user-images.githubusercontent.com/789159/216760229-89b6003e-3e02-4cbb-a08f-2972ba810582.jpg)

**Comment by Misplon** [comment]
An offset situation is happening in the reporting thread.

<img width="495" alt="Screenshot 2023-02-04 at 15 02 09" src="https://user-images.githubusercontent.com/789159/216769180-84adfb4e-6ab2-46f8-8241-ded95ba64d1a.png">

**Comment by AlexGStapleton** [comment]
I'm having trouble replicating this. Can you please send me a screenshot of your **Theme Settings > WooCommerce** settings?

**Comment by AlexGStapleton** [comment]
I've replicated this issue. It's specific to simple products and I was testing with a Grouped product.
