### ISSUE TITLE
Related posts in Single Posts

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#4]
To add related posts, we can either 

1. Add support for [YARRP](https://wordpress.org/plugins/yet-another-related-posts-plugin/)

2. Use our own query. Something like,

```
$args=array(
    'tag__in' => $tag_ids, // We can also use category__in
    'post__not_in' => array($post->ID),
    'posts_per_page'=>3,
    );
$my_query = new wp_query( $args );
```

What do you think?

**Comment by gregpriday** [comment]
I always prefer keeping themes light and supporting popular plugins, so my
vote is for supporting YARPP. We could use that query as a fallback though.

**Comment by Misplon** [comment]
@adiraomj Sounds like a plan, whenever you're ready.

**Comment by adiraomj** [comment]
@Misplon support for yarpp is already in place. I will now add a fallback.
I will also add an option in the blog section.
For the fallback do you guys think prefer finding related posts by `tags` or `categories`?
