### ISSUE TITLE
Blog Settings: Post Meta

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#45]
Not sure how much detail we want to add here. We could have a setting for each post meta item. Date, categories, tags. Actually, not too bad.

**Comment by adiraomj** [comment]
Will these settings apply to the archive pages as well?

**Comment by Misplon** [comment]
Yes, it's easiest to make them apply to both. What do you think?

**Comment by adiraomj** [comment]
Yes. That would be best. :)
