### ISSUE TITLE
Customizer Preview: Site title weight incorrect

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#51]
The site title weight is incorrect in the Customizer.

<img width="1403" alt="site-title" src="https://cloud.githubusercontent.com/assets/789159/20183750/0b093a62-a76f-11e6-831c-100b57781493.png">

**Comment by adiraomj** [comment]
Working fine for me. The font-weight is not showing any problems. I also cleared my cache.. Could not replicate issue.

**Comment by Misplon** [comment]
So when you view it in the Customizer, the site doesn't look like it does in my screenshot? Yours remains at 300 weight?

**Comment by Misplon** [comment]
@gregpriday can you check if this happening for you?

**Comment by adiraomj** [comment]
My font-weight remains at 300. No problems.. :)

**Comment by AlexGStapleton** [comment]
I can replicate the described issue in Chrome on Windows 10. I cannot however replicate it in FireFox. Are you using FireFox @adiraomj ?

**Comment by adiraomj** [comment]
I'm using Chrome on macOS Sierra.

**Customizer**
![customizer-title-weight](https://cloud.githubusercontent.com/assets/3372029/20389961/60673f80-acf2-11e6-8c73-0a899702a3c3.png)

**Frontend**
![frontend-title-weight](https://cloud.githubusercontent.com/assets/3372029/20389962/606a47ca-acf2-11e6-96f1-2f37e7c169fd.png)

I also tested with Safari and Firefox.

**Comment by AlexGStapleton** [comment]
Hm. That's weird. The only real difference I could find was that the customizer, for me, is using the Network version of Lato (from Google Fonts) and the main version is using the locally installed version.

![](https://i.imgur.com/bR4zJy6.png)

I'm unsure why that may be happening but it could be the cause of the issue. @Misplon Do either of you have Lato installed locally?

To clarify, you can see what's pictured by right clicking the site title and inspect it. Open the computed tab and scroll right down to the bottom.

![](https://i.imgur.com/L53blnk.gif)

**Comment by AlexGStapleton** [comment]
Oh, and the link for the Google Font URL seems to be encoded for me in the markup - is this happening for anyone else?

`<link rel='stylesheet' id='siteorigin-google-web-fonts-css'  href='//fonts.googleapis.com/css?family=Lato%3A400%7CMerriweather%3A400%2C700&#038;ver=4.6.1' type='text/css' media='all' />`

**Comment by Misplon** [comment]
@adiraomj You are seeing the issue. I can see the problem in your screenshot. The weight is different to the live site.

**Comment by Misplon** [comment]
@adiraomj Ahh perhaps not. Anyway, here is the problem on my side. See below:

<img width="1248" alt="01" src="https://cloud.githubusercontent.com/assets/789159/20393474/bd5c2e0c-ace4-11e6-9b0c-85f12fe63fad.png">

<img width="1113" alt="02" src="https://cloud.githubusercontent.com/assets/789159/20393477/c05b4aa2-ace4-11e6-8e0d-8907eb1edc10.png">

**Comment by Misplon** [comment]
@AlexGStapleton That's how it usually is rendered.

I have Lato installed with TypeKit. Ok, so you reckon that's causing this?

**Comment by AlexGStapleton** [comment]
I know. It's just weird that ones using the local version and the other is using the network version.

Regardless, I'm not too sure. I mean, it's possible. I think this idea all depends on if Adi has Lato installed locally or not. If he doesn't, he should try installing it to see if that causes the issue for him. If he does, disregard my reply.

**Comment by adiraomj** [comment]
Just installed Lato. Still cant replicate the issue.

![customizer-title-weight-2](https://cloud.githubusercontent.com/assets/3372029/20404157/b03e20aa-ad29-11e6-99d8-9d0607bb69d8.png)

**Comment by Misplon** [comment]
Resolved via: https://github.com/siteorigin/siteorigin-unwind/commit/a43bd5406d88c21b4c7be1480ffb4012e048a772.
