### ISSUE TITLE
Add a WooCommerce settings section

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#66]
Add a settings section for WooCommerce. Should we make it dependent on the plugin being activated?

**Comment by adiraomj** [comment]
What settings do we add? 

We could add a Quick View setting like we have for North.
Anything else?

We can make it dependent on the plugin being activated.

**Comment by Misplon** [comment]
Cool, let's add Quick View for now. When the mini-cart is ready we can add a setting for it.
