### ISSUE TITLE
Search results and featured images

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-unwind#7]
How do you think we can design the search results for posts that do not have a featured image?
1. we can have these posts aligned to the left.
2. we can have the users upload a fallback image in the settings.

**Comment by gregpriday** [comment]
I generally prefer just having the text take up the extra space, but we could also have a fallback image option available to users. This fallback image should only be used if a user has set one.

**Comment by adiraomj** [comment]
I have sent a PR for the search results. I have not implemented the fallback image. 

Which section should we put it in the customizer? The blog section or a new search section.

**Comment by Misplon** [comment]
I'm cool with putting it in the Blog section. @gregpriday you want it in the blog section or a new search section?

**Comment by Misplon** [comment]
@adiraomj We still going to go with a fallback in the blog section? Sound good? I will ask Ricardo to design one for us if so.

**Comment by adiraomj** [comment]
Yes, I'll go implement it next. I don't think we need a new design, the fallback image will just be replacing the featured image.

**Comment by Misplon** [comment]
@adiraomj Can we look into this one quite soon. We're quite close to the top of the admin queue. Thanks :)
