### ISSUE TITLE
WooCommerce: Add Gallery to Quick View

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#70]
The Quick View having the product gallery also would be a nice touch. Here's a quick (and super rough) mockup:

![](https://i.imgur.com/CrNoFm9.png)

Spacing and design obviously undecided.

**Comment by adiraomj** [comment]
How about just having just a slider instead of the the slider and thumbnails? What do you think?

**Comment by AlexGStapleton** [comment]
I'm okay with either, but it seems a tad weird to have a slider there and not on the page itself. Then again, the entire point of this view is to be minimal so it might be better. @Misplon Thoughts?
