### ISSUE TITLE
Masthead Widget area

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#83]
The Masthead widget area that works in a similar manner to the Vantage Masthead Widget area. It would remove the logo and the site description (if enabled) and in its place, the contents of the widget area would be output.

That would give users a large amount of control over that area _if_ desired, more than we could ever actually use and it'll give a lot of power to those that use the layout builder widget.

[Suggested here](https://siteorigin.slack.com/archives/themes/p1482914085000033).

----

What are your thoughts on calling it masthead or header? The former feels more consistent with Vantage and may prove to be consistent to those transitioning from Vantage.

**Comment by adiraomj** [comment]
We'll continue calling it Masthead.

**Comment by AlexGStapleton** [comment]
kk, updated the title.
